import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="text-2xl font-semibold tracking-tight font-heading">Terms of Service</h1>
      <div className="mt-6 space-y-4 text-sm text-muted-foreground">
        <p>
          By using MultiPersonas, you agree to the following:
        </p>
        <p>
          <strong className="text-foreground">What we do:</strong> MultiPersonas uses AI-powered
          browser automation to test websites for accessibility and usability issues. When you
          submit a URL, our system browses that site using automated browsers.
        </p>
        <p>
          <strong className="text-foreground">Your responsibility:</strong> Only submit URLs for
          sites you own or have permission to test. Do not use this service to scan sites without
          authorization.
        </p>
        <p>
          <strong className="text-foreground">AI-generated content:</strong> Audit findings are
          generated by AI and may contain inaccuracies. Do not rely on these findings as the sole
          basis for accessibility compliance decisions. Always verify results manually.
        </p>
        <p>
          <strong className="text-foreground">No guarantees:</strong> This service is provided
          as-is. We do not guarantee that audits will find all accessibility issues, or that
          findings are accurate.
        </p>
        <p className="text-xs text-muted-foreground/60">
          Last updated: May 2026. These terms will be expanded as the product develops.
        </p>
      </div>
      <div className="mt-8">
        <Link href="/" className="text-sm text-muted-foreground transition-colors hover:text-foreground">
          &larr; Back to home
        </Link>
      </div>
    </div>
  );
}
