import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Personaudit handles your data, authentication, and AI-generated audit results.",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="text-2xl font-semibold tracking-tight font-heading">Privacy Policy</h1>
      <div className="mt-6 space-y-4 text-sm text-muted-foreground">
        <p>
          Personaudit collects your email address and password hash for authentication.
          We use Supabase for auth and data storage.
        </p>
        <p>
          When you run an audit, we temporarily process the URL you provide by browsing it
          with automated browsers. We do not store screenshots or page content after the
          audit completes.
        </p>
        <p>
          Audit findings are generated by AI (Anthropic Claude) and sent through their API.
          Refer to{" "}
          <a
            href="https://www.anthropic.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-foreground underline underline-offset-4 hover:text-primary"
          >
            Anthropic&apos;s privacy policy
          </a>
          {" "}for how they handle data.
        </p>
        <p>
          We do not sell your data. We do not use analytics or tracking cookies.
        </p>
        <p className="text-xs text-muted-foreground/60">
          Last updated: May 2026. This policy will be expanded as the product develops.
        </p>
      </div>
      <div className="mt-8">
        <Link href="/" className="text-sm text-muted-foreground transition-colors hover:text-foreground">
          &larr; Back to home
        </Link>
      </div>
    </div>
  );
}
