import Link from "next/link";
import { Wordmark } from "@/components/forensic/wordmark";

const FOOTER_LINK =
  "py-2 transition-colors hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--ring)] rounded-sm";

const LINKS = [
  { href: "/for-agencies", label: "For agencies" },
  { href: "/grade", label: "Free grade" },
  { href: "/guides/ci-accessibility-gate", label: "CI gate" },
  { href: "/guides/wcag-checklist", label: "WCAG Checklist" },
  { href: "/guides/common-accessibility-issues", label: "Common Issues" },
  { href: "/guides/screen-reader-testing", label: "Screen Reader Testing" },
  { href: "mailto:hello@personaudit.com", label: "Contact", external: true },
  { href: "/accessibility", label: "Accessibility" },
  { href: "/privacy", label: "Privacy" },
  { href: "/terms", label: "Terms" },
] as const;

/**
 * Shared marketing footer — one link set, focus rings, AI disclaimer.
 * Optional footnotes slot for agency citations above the chrome.
 */
export function SiteFooter({
  footnotes,
  className = "",
}: {
  footnotes?: React.ReactNode;
  className?: string;
}) {
  return (
    <footer className={`border-t border-border px-6 py-8 ${className}`}>
      <div className="mx-auto max-w-6xl">
        {footnotes ? <div className="mb-8">{footnotes}</div> : null}
        <div
          className={`flex flex-col items-center gap-6 sm:flex-row sm:justify-between ${
            footnotes ? "border-t border-border pt-6" : ""
          }`}
        >
          <div className="text-center sm:text-left">
            <Wordmark className="text-sm text-foreground" />
            <p className="mt-1 text-xs text-muted-foreground">
              Built by{" "}
              <a
                href="https://github.com/forbiddenlink"
                target="_blank"
                rel="noopener noreferrer"
                className={`${FOOTER_LINK} inline-block`}
              >
                Elizabeth Stein
              </a>
            </p>
          </div>
          <nav
            aria-label="Footer"
            className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm text-muted-foreground"
          >
            {LINKS.map((link) =>
              "external" in link && link.external ? (
                <a key={link.href} href={link.href} className={FOOTER_LINK}>
                  {link.label}
                </a>
              ) : (
                <Link key={link.href} href={link.href} className={FOOTER_LINK}>
                  {link.label}
                </Link>
              ),
            )}
          </nav>
        </div>
        <p className="mt-4 text-center text-xs text-muted-foreground">
          Persona usability notes are generated by AI and should be verified manually.
          Accessibility violations come from axe-core and are deterministic.
        </p>
      </div>
    </footer>
  );
}
