name: Semgrep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v6.0.2
      - continue-on-error: true
        run: semgrep ci --config=auto --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: p/default p/security-audit p/secrets p/nextjs p/typescript p/react p/javascript
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: semgrep-sarif
          path: semgrep.sarif
          retention-days: 14
